name: Deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: keebo-ai/automerge-action:v1
