name: Deploy

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build
        run: docker build -t "keebo-ai/automerge-action:v1" .

      - name: Docker Tag
        run: docker tag "keebo-ai/automerge-action:v1" "keebo-ai/automerge-action:latest"

      - name: Docker Push
        run: docker push "ghcr.io:keebo-ai/automerge-action:v1"
